on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install pylint
          pip install -r requirements.txt
        if: ${{ steps.release.outputs.release_created }}

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Install flake8
        run: |
          pip install flake8
        if: ${{ steps.release.outputs.release_created }}

      - name: Analysing the code with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # execute overall flake8 scan
          flake8 . --count --statistics
        if: ${{ steps.release.outputs.release_created }}
